export const strings = {
    title: "BENEFITS",
    events: {
        title: "IRL events",
        body: "After selling out, our first event as a community will take place. The BBcon. This event will host other NFT Projects, Speakers, and Business talks. BBcon will change the way of hosting events giving the best value and experience for all guests."
    },
    airdrops: {
        title: "Airdrops",
        body: "Every month we will do airdrops to the most active and committed members. Airdrops will include ETH, BB Token (Season 2), and NFTs."
    },
    sales: {
        title: "Secondary Sales",
        body: "50% of secondary sales earnings will go directly into our treasury fund. This Fund will only be used to finance projects presented by Holders."
    },
    network: {
        title: "Exclusive Network",
        body: "BB will have its own Networking Dapp (Season 2). This Dapp will be used to connect Entrepreneurs, Freelancers, and Investors. BB NFT holders will have free access to the platform and no fees charged, ever. 20 % of the revenue generated by the platform will go directly into our treasury fund."
    },
    dreamProject: {
        title: "Fund your Project",
        subtitle: "Make your dream",
        body: "BB Holders can schedule a meeting, to present their project. After presenting your idea/business/project the Bearded Buddies team will be able to help you with funding and work teams along the way."
    },
    nextProject: {
        title: "Next Projects",
        body: "As entrepreneurs, our projects and ideas will never cease. Every BB NFT holder will have exclusivity on future projects."
    },
    ranks: {
        title: "Ranks",
        body: "Being an active member of the community will allow you to increase your rank. Higher ranks will become alpha buddies. This group of buddies will have access to sneak peeks, votes, and feedback on the next actions on the project."
    }

}